//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAllocationResource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectAllocationResource.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Operation did not succeed because the program cannot commit or quit a cell value change. 的本地化字符串。
        /// </summary>
        public static string Common_DataGridView_IsDirty {
            get {
                return ResourceManager.GetString("Common_DataGridView_IsDirty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 的本地化字符串。
        /// </summary>
        public static string Common_Field_Error {
            get {
                return ResourceManager.GetString("Common_Field_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total {0}% data have been processed. 的本地化字符串。
        /// </summary>
        public static string Common_Master_Export_Info {
            get {
                return ResourceManager.GetString("Common_Master_Export_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The No. {0} data are being exported to the excel file.. 的本地化字符串。
        /// </summary>
        public static string Common_Master_ExportToExcel_Info {
            get {
                return ResourceManager.GetString("Common_Master_ExportToExcel_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The No. {0} data are being imported. 的本地化字符串。
        /// </summary>
        public static string Common_Master_Import_Info {
            get {
                return ResourceManager.GetString("Common_Master_Import_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The No. {0} data are being read. 的本地化字符串。
        /// </summary>
        public static string Common_Master_ReadFromExcel_Info {
            get {
                return ResourceManager.GetString("Common_Master_ReadFromExcel_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The No. {0} data are being saved. 的本地化字符串。
        /// </summary>
        public static string Common_Master_Save_Info {
            get {
                return ResourceManager.GetString("Common_Master_Save_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The No. {0} data are being validated. 的本地化字符串。
        /// </summary>
        public static string Common_Master_Validate_Info {
            get {
                return ResourceManager.GetString("Common_Master_Validate_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行失败 的本地化字符串。
        /// </summary>
        public static string Common_Process_Failure {
            get {
                return ResourceManager.GetString("Common_Process_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行成功 的本地化字符串。
        /// </summary>
        public static string Common_Process_Success {
            get {
                return ResourceManager.GetString("Common_Process_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The No. {0} Row has the following error! 的本地化字符串。
        /// </summary>
        public static string Common_Row_Error {
            get {
                return ResourceManager.GetString("Common_Row_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你确定要退出系统吗？ 的本地化字符串。
        /// </summary>
        public static string Exit_Info {
            get {
                return ResourceManager.GetString("Exit_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工序码 &quot;{3}&quot; 已经存在！ 的本地化字符串。
        /// </summary>
        public static string Job_JobCode_Exists {
            get {
                return ResourceManager.GetString("Job_JobCode_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工序码不可以为空！ 的本地化字符串。
        /// </summary>
        public static string Job_JobCode_NotNull {
            get {
                return ResourceManager.GetString("Job_JobCode_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工序码 &quot;{3}&quot; 已重复！ 的本地化字符串。
        /// </summary>
        public static string Job_JobCode_Unique {
            get {
                return ResourceManager.GetString("Job_JobCode_Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工序名的长度必须在 {3} 和 {5}  字符之间！ 的本地化字符串。
        /// </summary>
        public static string Job_JobName_Length {
            get {
                return ResourceManager.GetString("Job_JobName_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分配比例应该输入数字！ 的本地化字符串。
        /// </summary>
        public static string Job_Percent_Format {
            get {
                return ResourceManager.GetString("Job_Percent_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分配比例的长度必须在 {3} 和 {5}  字符之间！ 的本地化字符串。
        /// </summary>
        public static string Job_Percent_Length {
            get {
                return ResourceManager.GetString("Job_Percent_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你确定要将选中的记录保存吗？ 的本地化字符串。
        /// </summary>
        public static string Job_SaveMessage {
            get {
                return ResourceManager.GetString("Job_SaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在加载工序数据！ 的本地化字符串。
        /// </summary>
        public static string Job_TaskMessage_Load {
            get {
                return ResourceManager.GetString("Job_TaskMessage_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在保存工序数据！ 的本地化字符串。
        /// </summary>
        public static string Job_TaskMessage_Save {
            get {
                return ResourceManager.GetString("Job_TaskMessage_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在验证工序数据！ 的本地化字符串。
        /// </summary>
        public static string Job_TaskMessage_Validate {
            get {
                return ResourceManager.GetString("Job_TaskMessage_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入用户ID！ 的本地化字符串。
        /// </summary>
        public static string Login_UserID_NoInput_Info {
            get {
                return ResourceManager.GetString("Login_UserID_NoInput_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户ID或密码不正确！请重试！ 的本地化字符串。
        /// </summary>
        public static string Login_UserPwd_Error {
            get {
                return ResourceManager.GetString("Login_UserPwd_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入用户密码 的本地化字符串。
        /// </summary>
        public static string Login_UserPwd_NoInput_Info {
            get {
                return ResourceManager.GetString("Login_UserPwd_NoInput_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分配比例应该输入数字！ 的本地化字符串。
        /// </summary>
        public static string Procedure_Percent_Format {
            get {
                return ResourceManager.GetString("Procedure_Percent_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分配比例的长度必须在 {3} 和 {5}  字符之间！ 的本地化字符串。
        /// </summary>
        public static string Procedure_Percent_Length {
            get {
                return ResourceManager.GetString("Procedure_Percent_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 专业码 &quot;{3}&quot; 已经存在！ 的本地化字符串。
        /// </summary>
        public static string Procedure_ProcedureCode_Exists {
            get {
                return ResourceManager.GetString("Procedure_ProcedureCode_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 专业码不可以为空！ 的本地化字符串。
        /// </summary>
        public static string Procedure_ProcedureCode_NotNull {
            get {
                return ResourceManager.GetString("Procedure_ProcedureCode_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 专业码 &quot;{3}&quot; 已重复！ 的本地化字符串。
        /// </summary>
        public static string Procedure_ProcedureCode_Unique {
            get {
                return ResourceManager.GetString("Procedure_ProcedureCode_Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 专业名的长度必须在 {3} 和 {5} 字符之间！ 的本地化字符串。
        /// </summary>
        public static string Procedure_ProcedureName_Length {
            get {
                return ResourceManager.GetString("Procedure_ProcedureName_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你确定要将选中的记录保存吗？ 的本地化字符串。
        /// </summary>
        public static string Procedure_SaveMessage {
            get {
                return ResourceManager.GetString("Procedure_SaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在加载专业数据！ 的本地化字符串。
        /// </summary>
        public static string Procedure_TaskMessage_Load {
            get {
                return ResourceManager.GetString("Procedure_TaskMessage_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在保存专业数据！ 的本地化字符串。
        /// </summary>
        public static string Procedure_TaskMessage_Save {
            get {
                return ResourceManager.GetString("Procedure_TaskMessage_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在验证专业数据！ 的本地化字符串。
        /// </summary>
        public static string Procedure_TaskMessage_Validate {
            get {
                return ResourceManager.GetString("Procedure_TaskMessage_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目码 &quot;{3}&quot; 已经存在！ 的本地化字符串。
        /// </summary>
        public static string Project_ProjectCode_Exists {
            get {
                return ResourceManager.GetString("Project_ProjectCode_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目名的长度必须在 {3} 和 {5} 字符之间！ 的本地化字符串。
        /// </summary>
        public static string Project_ProjectCode_Length {
            get {
                return ResourceManager.GetString("Project_ProjectCode_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目码不可以为空！ 的本地化字符串。
        /// </summary>
        public static string Project_ProjectCode_NotNull {
            get {
                return ResourceManager.GetString("Project_ProjectCode_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目码 &quot;{3}&quot; 已重复！ 的本地化字符串。
        /// </summary>
        public static string Project_ProjectCode_Unique {
            get {
                return ResourceManager.GetString("Project_ProjectCode_Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目名的长度必须在 {3} 和 {5} 字符之间！ 的本地化字符串。
        /// </summary>
        public static string Project_ProjectName_Length {
            get {
                return ResourceManager.GetString("Project_ProjectName_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你确定要将选中的记录保存吗？ 的本地化字符串。
        /// </summary>
        public static string Project_SaveMessage {
            get {
                return ResourceManager.GetString("Project_SaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在加载项目数据！ 的本地化字符串。
        /// </summary>
        public static string Project_TaskMessage_Load {
            get {
                return ResourceManager.GetString("Project_TaskMessage_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在保存项目数据！ 的本地化字符串。
        /// </summary>
        public static string Project_TaskMessage_Save {
            get {
                return ResourceManager.GetString("Project_TaskMessage_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在验证项目数据！ 的本地化字符串。
        /// </summary>
        public static string Project_TaskMessage_Validate {
            get {
                return ResourceManager.GetString("Project_TaskMessage_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你确定要将选中的记录保存吗？ 的本地化字符串。
        /// </summary>
        public static string ProjectAllocationCalc_SaveMessage {
            get {
                return ResourceManager.GetString("ProjectAllocationCalc_SaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分配比例应该输入数字！ 的本地化字符串。
        /// </summary>
        public static string Stage_Percent_Format {
            get {
                return ResourceManager.GetString("Stage_Percent_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分配比例的长度必须在 {3} 和 {5}  字符之间！ 的本地化字符串。
        /// </summary>
        public static string Stage_Percent_Length {
            get {
                return ResourceManager.GetString("Stage_Percent_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你确定要将选中的记录保存吗？ 的本地化字符串。
        /// </summary>
        public static string Stage_SaveMessage {
            get {
                return ResourceManager.GetString("Stage_SaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 阶段码 &quot;{3}&quot; 已经存在！ 的本地化字符串。
        /// </summary>
        public static string Stage_StageCode_Exists {
            get {
                return ResourceManager.GetString("Stage_StageCode_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 阶段码不可以为空！ 的本地化字符串。
        /// </summary>
        public static string Stage_StageCode_NotNull {
            get {
                return ResourceManager.GetString("Stage_StageCode_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 阶段码 &quot;{3}&quot; 已重复！ 的本地化字符串。
        /// </summary>
        public static string Stage_StageCode_Unique {
            get {
                return ResourceManager.GetString("Stage_StageCode_Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 阶段名的长度必须在 {3} 和 {5} 字符之间！ 的本地化字符串。
        /// </summary>
        public static string Stage_StageName_Length {
            get {
                return ResourceManager.GetString("Stage_StageName_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在加载阶段数据！ 的本地化字符串。
        /// </summary>
        public static string Stage_TaskMessage_Load {
            get {
                return ResourceManager.GetString("Stage_TaskMessage_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在保存阶段数据！ 的本地化字符串。
        /// </summary>
        public static string Stage_TaskMessage_Save {
            get {
                return ResourceManager.GetString("Stage_TaskMessage_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在验证阶段数据！ 的本地化字符串。
        /// </summary>
        public static string Stage_TaskMessage_Validate {
            get {
                return ResourceManager.GetString("Stage_TaskMessage_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你确定要将选中的记录保存吗？ 的本地化字符串。
        /// </summary>
        public static string User_SaveMessage {
            get {
                return ResourceManager.GetString("User_SaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在加载用户数据！ 的本地化字符串。
        /// </summary>
        public static string User_TaskMessage_Load {
            get {
                return ResourceManager.GetString("User_TaskMessage_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在保存用户数据！ 的本地化字符串。
        /// </summary>
        public static string User_TaskMessage_Save {
            get {
                return ResourceManager.GetString("User_TaskMessage_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在验证用户数据！ 的本地化字符串。
        /// </summary>
        public static string User_TaskMessage_Validate {
            get {
                return ResourceManager.GetString("User_TaskMessage_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户码 &quot;{3}&quot; 已经存在！ 的本地化字符串。
        /// </summary>
        public static string User_UserCode_Exists {
            get {
                return ResourceManager.GetString("User_UserCode_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户码不可以为空！ 的本地化字符串。
        /// </summary>
        public static string User_UserCode_NotNull {
            get {
                return ResourceManager.GetString("User_UserCode_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户码 &quot;{3}&quot; 已重复！ 的本地化字符串。
        /// </summary>
        public static string User_UserCode_Unique {
            get {
                return ResourceManager.GetString("User_UserCode_Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 你确定要将选中的记录保存吗？ 的本地化字符串。
        /// </summary>
        public static string Worker_SaveMessage {
            get {
                return ResourceManager.GetString("Worker_SaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在加载员工数据！ 的本地化字符串。
        /// </summary>
        public static string Worker_TaskMessage_Load {
            get {
                return ResourceManager.GetString("Worker_TaskMessage_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在保存员工数据！ 的本地化字符串。
        /// </summary>
        public static string Worker_TaskMessage_Save {
            get {
                return ResourceManager.GetString("Worker_TaskMessage_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在验证员工数据！ 的本地化字符串。
        /// </summary>
        public static string Worker_TaskMessage_Validate {
            get {
                return ResourceManager.GetString("Worker_TaskMessage_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 员工码 &quot;{3}&quot; 已经存在！ 的本地化字符串。
        /// </summary>
        public static string Worker_WorkerCode_Exists {
            get {
                return ResourceManager.GetString("Worker_WorkerCode_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 员工名的长度必须在 {3} 和 {5} 字符之间！ 的本地化字符串。
        /// </summary>
        public static string Worker_WorkerCode_Length {
            get {
                return ResourceManager.GetString("Worker_WorkerCode_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 员工码不可以为空！ 的本地化字符串。
        /// </summary>
        public static string Worker_WorkerCode_NotNull {
            get {
                return ResourceManager.GetString("Worker_WorkerCode_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 员工码 &quot;{3}&quot; 已重复！ 的本地化字符串。
        /// </summary>
        public static string Worker_WorkerCode_Unique {
            get {
                return ResourceManager.GetString("Worker_WorkerCode_Unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 员工名的长度必须在 {3} 和 {5} 字符之间！ 的本地化字符串。
        /// </summary>
        public static string Worker_WorkerName_Length {
            get {
                return ResourceManager.GetString("Worker_WorkerName_Length", resourceCulture);
            }
        }
    }
}
